CREATE DATABASE todoDatabase;

CREATE TABLE Todo(
    id SERIAL PRIMARY KEY, 
    title VARCHAR(255),
    description VARCHAR(255),
    status BOOLEAN,
     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);